---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # allows you to use another pre-made action
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # we need to use this check out step here to make use the code is
      # available for us to run the next step on
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Run Lint
        run: docker-compose run --rm app sh -c "flake8"
# successful exit for linux is zero
# if any of these fail then the job that is running is going to fail
# docker compose comes preinstalled on the Ubuntu 20.04 runner